### ISSUE TITLE
Makefile has hardcoded values.

### ISSUE THREAD

**Issue by richc-admin-gcai** [josephcolton/tcpping#1]
Hi,

I was looking at this and the Makefile has hardcoded values, so it would be worth this taking variables; such as provided by this match

--- Makefile	2024-12-03 10:00:00.000000000 +0000
+++ Makefile	2024-12-03 10:10:00.000000000 +0000
@@ -1,11 +1,19 @@
-CC = gcc
+CC ?= gcc
+CFLAGS ?= -O2 -Wall
+LDFLAGS ?=
+PREFIX ?= /usr/local
 
-tcpping: tcpping.c
-        $(CC) tcpping.c -o tcpping
+TARGET = tcpping
 
-install: tcpping
-        sudo cp tcpping /usr/bin/
+all: $(TARGET)
+
+$(TARGET): $(TARGET).c
+	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $<
+
+install: $(TARGET)
+	install -Dm755 $(TARGET) $(PREFIX)/bin/$(TARGET)
 
 clean:
-        rm tcpping
+	rm -f $(TARGET)

As that way you can change compiler, options and set a PREFIX

**Comment by josephcolton** [comment]
The changes were made to address this.

**Comment by josephcolton** [comment]
Thank you for the suggestion.  The Makefile was not something I spent a lot
of time looking at, but something that I probably needed to look at.

Joseph
